from .random_agent import RandomAgent
from .human_agent import HumanAgent
from .student_agent import StudentAgent
from .greedy_corners_agent import StudentAgent
from .alpha_beta_agent import StudentAgent
from .minimax_agent import StudentAgent
from .mcts_agent import StudentAgent
from .alpha_beta_agent_final import AlphaBetaAgentFinal
from .alpha_beta_agent_final_copy import AlphaBetaAgentFinal
